<a href="https://colab.research.google.com/github/alessandrossC/ML-for-people/blob/main/%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import random
vector1 = np.array([random.uniform(0, 1) for _ in range(10)])
print(vector1)

vector2 = np.random.rand(10)
print (vector2)

[0.21133074 0.02276067 0.90457497 0.5352499  0.99592319 0.12254779
 0.40668807 0.52310308 0.53141948 0.2988872 ]
[0.31018625 0.70887258 0.20812849 0.13747005 0.00158192 0.43865336
 0.87164478 0.78233519 0.91492241 0.74017435]


In [2]:
matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])
print("\nMatrix:")
print(matrix)
print("Розмір векрора1:", vector1.shape)
print("Розмір векрора2:", vector2.shape)
print("Розмір матриці:", matrix.shape)


Matrix:
[[11 20 29]
 [14 23 32]
 [17 26 35]]
Розмір векрора1: (10,)
Розмір векрора2: (10,)
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [3]:
vector1_add_10 = np.round(vector1 + 10, 2)
print("\nVector1 після додавання 10 та округлення:", vector1_add_10)
matrix_2 = matrix * 2
print("\n Матриця після множення на 2:")
print(matrix_2)
vector2 = np.square(vector1)
print("\n Новий вектор, який містит квадрат кожного vector1 ", vector2)


Vector1 після додавання 10 та округлення: [10.21 10.02 10.9  10.54 11.   10.12 10.41 10.52 10.53 10.3 ]

 Матриця після множення на 2:
[[22 40 58]
 [28 46 64]
 [34 52 70]]

 Новий вектор, який містит квадрат кожного vector1  [4.46606817e-02 5.18048049e-04 8.18255870e-01 2.86492452e-01
 9.91862994e-01 1.50179610e-02 1.65395187e-01 2.73636836e-01
 2.82406660e-01 8.93335584e-02]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [4]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [5]:
# Завданн1
A1 = A.T
B1 = B.T
result_matrix = np.dot(A1, B1)
print("Результат множення матриць А та B:")
print(result_matrix)

Результат множення матриць А та B:
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [6]:
# Завдання2
final_result = np.dot(result_matrix, C)

final_result

array([[0.2034],
       [0.2846]])

In [7]:
# Завдання3
result_matrix_D = np.dot(result_matrix, D)
result_matrix_D

array([[0.2034, 0.7281],
       [0.2846, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [8]:
result_matrix_transposed = result_matrix.T
vector_transposed = vector1.T
print("Трранспонована матриця:")
print(result_matrix_transposed)
print("Розмір матриці після транспонування:", result_matrix_transposed.shape)
print("\nТрранспонований вектор:")
print(vector_transposed)
print("Розмір вектору після транспонування:", vector_transposed.shape)

Трранспонована матриця:
[[0.7281 0.5202]
 [0.2034 0.2846]]
Розмір матриці після транспонування: (2, 2)

Трранспонований вектор:
[0.21133074 0.02276067 0.90457497 0.5352499  0.99592319 0.12254779
 0.40668807 0.52310308 0.53141948 0.2988872 ]
Розмір вектору після транспонування: (10,)


Транспонування одномірного вектора не змінює його форму. Результат залишається таким самим

In [10]:
# Додавання осі для створення column_vector
column_vector = np.expand_dims(vector1, axis=1)

print("column_vector:")
print(column_vector)
print("Розмір column_vector:", column_vector.shape)

# Транспонування column_vector
transposed_column_vector = column_vector.T
print("transposed_column_vector")
print(transposed_column_vector)
print("Розмір транспонованого column_vector:", transposed_column_vector.shape)

column_vector:
[[0.21133074]
 [0.02276067]
 [0.90457497]
 [0.5352499 ]
 [0.99592319]
 [0.12254779]
 [0.40668807]
 [0.52310308]
 [0.53141948]
 [0.2988872 ]]
Розмір column_vector: (10, 1)
transposed_column_vector
[[0.21133074 0.02276067 0.90457497 0.5352499  0.99592319 0.12254779
  0.40668807 0.52310308 0.53141948 0.2988872 ]]
Розмір транспонованого column_vector: (1, 10)


Початковий вектор vector є одномірним, тому його форма (10,).
Використання np.expand_dims додало новий вимір, перетворивши його на вектор-стовпець (10,1).
Транспонування column_vector перетворило його у вектор-рядок (1,10).
Тепер форма вектора змінюється в залежності від кількості осей.